### ISSUE TITLE
No such module 'ZIPFoundation'

### ISSUE THREAD

**Issue by GrupoGO** [DP-3T/dp3t-sdk-ios#108]
ExposureNotificationMatcher imports ZIPFoundation
You need to add a dependency at DP3TSDK.podspec: spec.dependency 'ZIPFoundation', '~> 0.9'?

**Comment by Shiaulis** [comment]
Yep, the same issue for me. Any plans to fix it?

**Comment by alexandru-lazar** [comment]
I have no issues compiling the project using Xcode 11.5 (official release). I tried develop branch and it worked as intended.

**Comment by Shiaulis** [comment]
@alexandru-lazar it was my wrong assumption that this is somehow connected with Xcode update. For some reason it works for those who used the previous version of the library, but for new installs it lacks this dependency. At least by using Cocoapods

**Comment by stmitt** [comment]
I pushed a new cocoapods version which contains the needed dependency. Let me know if this fixes your issue.

**Comment by Shiaulis** [comment]
Maybe I'm doing smth wrong, but I cannot get the update. With `pod oudated` it shows new changes, but telling that it cannot be updated. We didn't specify version in `Podfile`
![image](https://user-images.githubusercontent.com/13601748/83007159-f39dfd00-a01b-11ea-8bff-da22d0a027f4.png)
`pod deintegrate` + `pod install` also didn't help. Is there any extra steps I'm missing?

**Comment by alexandru-lazar** [comment]
@Shiaulis Try this, please.
1. Remove the pod from pod file.
2. Run in terminal pod install.
3. Add again the pod but this time with pod 'DP3TSDK'.

I just did these steps and it worked.

**Comment by Shiaulis** [comment]
I feel like silly person but it didn't help 🤦 Moreover, I don't see ZIPFoundation in sub dependencies while install:
![image](https://user-images.githubusercontent.com/13601748/83010121-75902500-a020-11ea-9247-fe03d776e671.png)
And after that running `pod oudated` shows me that I still have some changes:
![image](https://user-images.githubusercontent.com/13601748/83010203-93f62080-a020-11ea-9e09-16e39726b5b6.png)
@alexandru-lazar , maybe you specified version in your `Podfile`? ir is just plain `  pod 'DP3TSDK'?

**Comment by alexandru-lazar** [comment]
I did not specify the version in the pod file. 
Try doing a "pod cache clean --all".
Moreover try to specify the 0.4.0 version in pod file if everything else fails.

**Comment by Shiaulis** [comment]
Okay I found the issue, again silly me. Before, we had `platform :ios, '11.0'` and since latest DP3TSDK is looking for the latest version of iOS , I didn't get an update. I specified the latest iOS version in `Podfile` and now it works! Thanks
